### ISSUE TITLE
Choice of nationalities from limited vocabulary

### ISSUE THREAD

**Issue by danohuiginn** [openc/WhoControlsIt#15]
Dropdown, autocomplete?

[we maybe want it to be _possible_ to enter free-text nationality, but to funnel most people into using something obvious]

**Comment by CountCulture** [comment]
We can maybe use countries gem for this.

**Comment by elf-pavlik** [comment]
long time ago i made small contribution to RoR based project and used i18n_data gem, maybe would also work here?
https://github.com/dennisreimann/masquerade/commits?author=elf-pavlik

**Comment by bensymonds** [comment]
We have launched http://openownership.org now so no more development on WhoControlsIt is planned.

For what it's worth - we did end up using https://github.com/hexorx/countries!
