### ISSUE TITLE
inconsistent seed data

### ISSUE THREAD

**Issue by elf-pavlik** [openc/WhoControlsIt#22]
### base.yml

* duplicated *company_number* 01098034 for two companies with different names
* *company_number* sometimes string sometimes number

### drc_bo.yml
* details uses string with number followed by % sign while base.yml uses only string with number

**Comment by dcabo** [comment]
Additionally, some people and entities are duplicated. For example "Lambert djunga" shows at least twice in the loaded data.

**Comment by CountCulture** [comment]
Fixed dup company numbers.
